  <div class="post__share">
      <ul>
          <li>Share this post</li>
          <li>
              <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo get_permalink(); ?>">
                  <svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                      <!--Generated by IJSVG (https://github.com/iconjar/IJSVG)-->
                      <path d="M7.5,3h9.004c2.483,0 4.496,2.013 4.496,4.496v9.009c0,2.482 -2.013,4.495 -4.496,4.495h-9.008c-2.483,0 -4.496,-2.013 -4.496,-4.496v-9.004c0,-2.485 2.015,-4.5 4.5,-4.5Z" stroke-linecap="round" stroke-width="1.5" fill-rule="evenodd" stroke="#747489" fill="none" stroke-linejoin="round"></path>
                      <path fill="none" stroke="#747489" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M11.1,12.9h5.4"></path>
                      <path d="M16.5,8.4h-0.945c-1.466,0 -2.655,1.189 -2.655,2.655v0.945v9" stroke-linecap="round" stroke-width="1.5" stroke="#747489" fill="none" stroke-linejoin="round"></path>
                      <path fill="none" d="M0,0h24v24h-24Z" transform="matrix(6.12323e-17,-1,1,6.12323e-17,0,24)"></path>
                  </svg>
              </a>
          </li>
          <li>
              <a href="https://www.linkedin.com/shareArticle?mini=true&url=<?php echo get_permalink(); ?>&title=<?php the_title(); ?>&summary=&source=">
                  <svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                      <!--Generated by IJSVG (https://github.com/iconjar/IJSVG)-->
                      <path d="M7.5,3h9.004c2.483,0 4.496,2.013 4.496,4.496v9.009c0,2.482 -2.013,4.495 -4.496,4.495h-9.008c-2.483,0 -4.496,-2.013 -4.496,-4.496v-9.004c0,-2.485 2.015,-4.5 4.5,-4.5Z" stroke-linecap="round" stroke-width="1.5" fill-rule="evenodd" stroke="#747489" fill="none" stroke-linejoin="round"></path>
                      <path fill="none" stroke="#747489" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M8.12,11.1v5.4"></path>
                      <g stroke-linecap="round" stroke-width="1.5" stroke="#747489" fill="none" stroke-linejoin="round">
                          <path d="M11.719,16.5v-3.15c0,-1.243 1.007,-2.25 2.25,-2.25v0c1.243,0 2.25,1.007 2.25,2.25v3.15">
                          </path>
                          <path d="M8.118,7.838c-0.124,0 -0.225,0.101 -0.224,0.225c0,0.124 0.101,0.225 0.225,0.225c0.124,0 0.225,-0.101 0.225,-0.225c0,-0.125 -0.101,-0.225 -0.226,-0.225">
                          </path>
                      </g>
                      <path fill="none" d="M0,0h24v24h-24Z" transform="matrix(6.12323e-17,-1,1,6.12323e-17,0,24)"></path>
                  </svg>
              </a>
          </li>
          <li>
              <a href="https://twitter.com/home?status=<?php echo get_permalink(); ?>">
                  <svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                      <!--Generated by IJSVG (https://github.com/iconjar/IJSVG)-->
                      <path d="M19.2,9.35c0,6.3 -3.6,10.8 -9.9,10.8c-3.6,0 -5.043,-1.879 -6.3,-3.6m8.88178e-16,3.55271e-15c0.029,-0.005 2.7,-0.9 2.7,-0.9c-3.006,-3.039 -3.234,-7.54 -0.9,-10.8c1.107,2.059 3.174,3.959 5.4,4.5c0.086,-2.6 1.849,-4.5 4.5,-4.5c1.805,0 2.867,0.688 3.6,1.8h2.7l-1.8,2.7" stroke-linecap="round" stroke-width="1.5" fill-rule="evenodd" stroke="#747489" fill="none" stroke-linejoin="round"></path>
                      <path fill="none" d="M0,0h24v24h-24Z" transform="matrix(6.12323e-17,-1,1,6.12323e-17,0,24)"></path>
                  </svg>
              </a>
          </li>
          <li>
              <a href="mailto:?&subject<?php the_title(); ?>=&body=<?php echo get_permalink(); ?>">
                  <svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                      <!--Generated by IJSVG (https://github.com/iconjar/IJSVG)-->
                      <g stroke-linecap="round" stroke-width="1.5" stroke="#747489" fill="none" stroke-linejoin="round">
                          <path d="M7.5,3h9.004c2.483,0 4.496,2.013 4.496,4.496v9.009c0,2.482 -2.013,4.495 -4.496,4.495h-9.008c-2.483,0 -4.496,-2.013 -4.496,-4.496v-9.004c0,-2.485 2.015,-4.5 4.5,-4.5Z">
                          </path>
                          <path d="M15.409,16.545h-6.818c-1.256,0 -2.273,-1.017 -2.273,-2.273v-4.545c0,-1.256 1.017,-2.273 2.273,-2.273h6.818c1.256,0 2.273,1.017 2.273,2.273v4.545c0,1.256 -1.017,2.273 -2.273,2.273Z">
                          </path>
                          <path d="M17.016,8.12l-3.595,3.595v0c-0.784,0.784 -2.057,0.784 -2.841,0v0l-3.596,-3.595"></path>
                          <path d="M10.58,11.716l-3.852,3.852"></path>
                          <path d="M13.42,11.716l3.852,3.852"></path>
                      </g>
                      <path fill="none" d="M0,24v-24h24v24h-24Z"></path>
                  </svg>
              </a>
          </li>
      </ul>
  </div>